library('ggplot2')
library('pheatmap')
library(readr)
library(readxl)
library(dplyr)
library(ggplot2)
library(ggrepel)

setwd('D:/项目/精浆cfRNA/成果/文章/投稿/Github')
################# Analysis of seminal plasma for manuscript

########################### Figure 1
####Fig1A. illustrator generated by Biorender

########Fig1B. percentage of various detected RNAs
stat_normal <- data.frame(read.table('D:/项目/精浆cfRNA/分析结果/Stat/QC_stat_Normal.txt',header = T,row.names = 1))
RNA_mean <- apply(cbind(stat_normal$miRNA,stat_normal$tRNA,stat_normal$piRNA,stat_normal$mRNA,stat_normal$otherRNA),2,mean)
lib_RNA <- data.frame(type=c('miRNA','tRNA','piRNA','mRNA/lncRNA','otherRNA'),pct=RNA_mean/sum(RNA_mean)*100)
lib_RNA$type <- factor(lib_RNA$type, levels = rev(as.character(lib_RNA$type)))
pdf('Fig1B.RNA_pct_pie.pdf')
p <- ggplot(lib_RNA, aes(x="", y=pct, fill=type)) +
  geom_bar(stat="identity", width=1)+ 
  coord_polar("y", start=0)+
  theme_void()+
  guides(fill = guide_legend(reverse = TRUE))
p+ theme(legend.text = element_text(size=20),legend.title  = element_text(size=20))
dev.off()

#######Fig1C. piRNA
len_5base <- data.frame(read.table('Normal_len_5base.txt',header = T,row.names = 1))
pdf('Fig1C.piRNA_len_5base.pdf',width = 8,height = 5,pointsize = 10)
barplot(t(data.matrix(len_5base))/1000/104,ylab='Average number of piRNA(X1000)',col=c('red','blue','green','orange'))
legend("topleft",legend =c('G','U','C','A'),cex=0.8,pch=15,col=c('orange','green','blue','red'))
dev.off()


#######Fig1D.boxplot of tRNA abundance  
tRNA <- data.frame(read.table('tRNA_merge_TPM.txt',header = T,check.names = FALSE),check.names = FALSE)
tRNA_exp <- tRNA[, 1:(ncol(tRNA)-3)]
#boxplot of top10 tRNAs
library('colorspace')
Nor_tRNA <- t(data.matrix(rbind(tRNA_exp[1:101,])))
ave <- apply(Nor_tRNA,1,mean)
Nor_tRNA <- data.frame(cbind(Nor_tRNA,ave))
colnames(Nor_tRNA) <- c(rownames(tRNA)[1:101],'AVE')
#rownames(Nor_tRNA) <- rownames(tRNA)
Nor_tRNA <- Nor_tRNA[order(Nor_tRNA$AVE,decreasing = F),]
pdf('Fig1D.tRNA_top10_bxp.pdf',width=4,height = 6)
par(mar=c(8,4,2,2))
boxplot(t(log2(Nor_tRNA[1:101])[40:49,]), horizontal = T,ylab='log2(TPM)',pch='.',las=2,col=diverge_hsv(10))
dev.off()

###Fig1E. illustrator generated by Biorender

######## Fig1F. Original scores
origin <- read_xlsx('TableS3. Origin score of CIBERSOTx using scRNA data of testis.xlsx')
origin <- origin %>%
  mutate(across(2:13, as.numeric)) 
origin_N <- data.frame(score = c(data.matrix(origin[1:101,2:13])),
                       cells = as.factor(c(rep(colnames(origin)[2:13],each=101))))
pdf('Fig1F.Origin_score_bxp.pdf',pointsize = 12)
ggplot(origin_N,aes(x=reorder(cells,score,decreasing=T), y=score,fill=reorder(cells,score,decreasing=T)))+
  geom_boxplot(outlier.size = 0.6)+
  theme_bw() + theme(panel.grid=element_blank())+
  labs(y="Score", x="Cell type", subtitle="") +theme(legend.position="none")
dev.off()


################################ Figure 2 #######################
###Fig 2A boxplot of RNA ratio
stat_total <- data.frame(read.table('QC_stat_CTL_update_6.27.txt',header = T,row.names = 1))
stat_RNA <- stat_total[1:419,6:10]
stat_RNA_pct <- data.frame(group = rep(groups[1:419],5),
                           RNA = rep(c('miRNA','tRNA','piRNA','mRNA/lncRNA','otherRNA'),times=c(419,419,419,419,419)),
                           ratio = c(stat_RNA$miRNA,stat_RNA$tRNA,stat_RNA$piRNA,stat_RNA$mRNA,stat_RNA$otherRNA))
stat_RNA_pct$RNA <- factor(stat_RNA_pct$RNA, levels = rev(as.character(stat_RNA_pct$RNA)))
stat_RNA_pct$group <- factor(stat_RNA_pct$group,levels = c('NOR','AZS','OLI','AZO'))
p1<-ggplot(stat_RNA_pct, aes(fill=factor(group), y=ratio,x=factor(RNA,level=c('miRNA','tRNA','piRNA','mRNA/lncRNA','otherRNA')))) +
  geom_boxplot(show.legend = NA)+ 
  #  coord_polar("y", start=0)+
  theme_void()
pdf('RNA_ratio_boxplot.pdf')
p1+ theme(legend.text = element_text(size=10),legend.title  = element_blank(),
          axis.text = element_text(),axis.line = element_line(),axis.ticks = element_line())
dev.off()

####Fig2B number of DAGs
df_gene_num <- read.table(file = "df_gene_num.txt",
                          sep = "\t",row.names = 1,header = T)
## 2.1 data processing
df_gene_num$group <- rownames(df_gene_num)
df_gene_num2 <- pivot_longer(df_gene_num,cols = c("Up_num","Down_num"),
                             values_to = "gene_num",names_to = "updown")
df_up <- df_gene_num2[df_gene_num2$updown=="Up_num",] %>% 
  arrange(group)
df_down <- df_gene_num2[df_gene_num2$updown=="Down_num",] %>% 
  arrange(group)
df_down$gene_num <- -df_down$gene_num
## 2.3 barplot2
df_gene_num3 <- df_gene_num[-c(grep("mlncRNA",df_gene_num$group),
                               grep("tRNA_merge",df_gene_num$group)),] %>% 
  mutate(group2=sub("^(.*?)_.*$", "\\1", group)) %>% 
  mutate(group2=factor(group2,levels=c("miRNA","tRNA","piRNA","mRNA","lncRNA"))) %>% 
  mutate(group3=sub("^.*_.*_(.*)_.*$", "\\1", group)) %>% 
  mutate(group3=gsub("CF.R","AST",group3)) %>% 
  mutate(group3=gsub("CF.S","OLI",group3)) %>% 
  mutate(group3=gsub("CF.W","AZO",group3)) %>% 
  mutate(group3=factor(group3,levels=c("AST","OLI","AZO"))) %>% 
  mutate(group=factor(group,levels=.$group[order(.$group2)]))
df_gene_num4 <- pivot_longer(df_gene_num3,cols = c("Up_num","Down_num"),
                             values_to = "gene_num",names_to = "updown")
df_up <- df_gene_num4[df_gene_num4$updown=="Up_num",] %>% 
  arrange(group)
df_down <- df_gene_num4[df_gene_num4$updown=="Down_num",] %>% 
  arrange(group)
df_down$gene_num <- -df_down$gene_num
pdf(file = "Fig2B_df_gene_num2.pdf",
    width=7,height = 5)
ggplot(data = df_gene_num4)+
  geom_bar(data = df_up,aes(x=group,y=gene_num,fill='A'),
           stat = "identity",position = "identity")+
  geom_bar(data = df_down,aes(x=group,y=gene_num,fill="B"),
           stat = "identity",position = "identity")+
  geom_text(data = df_up,aes(x=group,y=gene_num+100,label=gene_num),size=2.5)+
  geom_text(data = df_down,aes(x=group,y=gene_num-100,label=-gene_num),size=2.5)+
  facet_grid(.~group2,scales = "free")+
  theme_test()+
  scale_x_discrete(labels=df_gene_num3$group3)+
  scale_y_continuous(expand = c(0.1,0,0.1,0),breaks = c(-3000,-2000,-1000,0,1000),
                     labels = c(3000,2000,1000,0,1000))+
  scale_fill_manual(name="Group",
                    values = c('A' = '#ED0000FF', "B" = '#00468BFF'), 
                    labels = c('Up', 'Down'))+
  labs(x="",y="",title='')+
  theme(# legend.position = "none",
    # panel.grid = element_blank(),
    plot.margin = margin(0.4,0.4,0.4,0.4,'cm'),
    plot.title = element_text(size = 16,face = 'bold',hjust = 0.5),
    axis.title = element_text(size = 12,face = 'bold',hjust = 0.5),
    # axis.text.x = element_text(size = 10,face = 'bold',hjust = 1,angle = 45),
    axis.text.x = element_text(size = 8,face = 'bold',hjust = 1,angle = 45),
    axis.text.y  = element_text(size = 8,face = 'bold',hjust = 0.5),
    legend.title = element_text(size = 10,face = 'bold',hjust = 0),
    legend.text = element_text(size = 8,face = 'bold',hjust = 0))
dev.off()

##Fig 2C-D dotplot of GSEA
suppressMessages({
  library(tidyverse)
  library(scales)
  library(simplifyEnrichment)
})

### 0.筛选up_pathway和down_pathway ####
AZS_pathway <- read.table(file = "./AZS/GSEA_GO_BP_res.txt",sep = "\t",header = T,row.names = NULL,fill = T)
OLI_pathway <- read.table(file = "./OLI/GSEA_GO_BP_res.txt",sep = "\t",header = T,row.names = NULL,fill = T)
AZO_pathway <- read.table(file = "./AZO/GSEA_GO_BP_res.txt",sep = "\t",header = T,row.names = NULL,fill = T)
AZS_pathway_up <- AZS_pathway %>% 
  filter(p.adjust<0.05) %>% 
  filter(NES>0) %>% 
  arrange(-NES) %>% 
  slice(1:16)
OLI_pathway_up <- OLI_pathway %>%
  filter(p.adjust<0.05) %>% 
  filter(NES>0) %>% 
  arrange(-NES) %>% 
  slice(1:16)
AZO_pathway_up <- AZO_pathway %>%
  filter(p.adjust<0.05) %>%
  filter(NES>0) %>%
  arrange(-NES) %>% 
  slice(1:16)
all_id_up_df <- bind_rows(AZS_pathway_up,OLI_pathway_up,AZO_pathway_up) %>% 
  dplyr::select(1,2) %>% 
  unique()
all_id_up <- unique(c(AZS_pathway_up$ID,OLI_pathway_up$ID,AZO_pathway_up$ID))
length(all_id_up) # 共有多少上调通路
AZS_pathway_down <- AZS_pathway %>%
  filter(p.adjust<0.05) %>%
  filter(NES<0) %>%
  arrange(NES) %>% 
  slice(1:13)
OLI_pathway_down <- OLI_pathway %>%
  filter(p.adjust<0.05) %>%
  filter(NES<0) %>%
  arrange(NES) %>% 
  slice(1:13)
AZO_pathway_down <- AZO_pathway %>%
  filter(p.adjust<0.05) %>%
  filter(NES<0) %>%
  arrange(NES) %>% 
  slice(1:13)
all_id_down_df <- bind_rows(AZS_pathway_down,OLI_pathway_down,AZO_pathway_down) %>% 
  dplyr::select(1,2) %>% 
  unique()
all_id_down <- unique(c(AZS_pathway_down$ID,OLI_pathway_down$ID,AZO_pathway_down$ID))
length(all_id_down) # 共有多少下调通路
write.table(all_id_up_df,file = "./outputdata/up_unique.txt",
            row.names = F,col.names = F,sep = "\t",quote = F)
write.table(all_id_down_df,file = "./outputdata/down_unique.txt",
            row.names = F,col.names = F,sep = "\t",quote = F)

# 通过AI，将up通路分为三类，这三类是根据以前AI分的：
# Chemical stimulation and sensation
# Cell differentiation and organ development
# Immune system regulation
# 通过AI，将down通路分为四类
# Cell division and chromosome division
# Germ cell formation
# Reproduction and development
# Other


### 2.ggplot data ####
up_cluster <- read.table(file = "./inputdata/up_GOterm.txt",sep = "\t",header = T,
                         row.names = NULL)
down_cluster <- read.table(file = "./inputdata/down_GOterm.txt",sep = "\t",header = T,
                           row.names = NULL)
grps <- c("AZS","OLI","AZO")
for (i_grp in grps) {
  df <- read.table(file = paste0("../GSEA_GO_KEGG3/",i_grp,"/GSEA_GO_BP_res.txt"),
                   sep = "\t",header = T,row.names = NULL,fill = T)
  up_df <- df[match(up_cluster$id,df$ID),] %>% 
    merge(up_cluster,.,by.y="ID",by.x="id",all.y = T)
  down_df <- df[match(down_cluster$id,df$ID),] %>% 
    merge(down_cluster,.,by.y="ID",by.x="id",all.y = T)
  assign(paste0(i_grp,"_up"),up_df)
  assign(paste0(i_grp,"_down"),down_df)
}
all_up <- rbind(AZS_up,OLI_up,AZO_up) %>% 
  mutate(p_adj=-log10(p.adjust)) %>% 
  na.omit() %>% 
  filter(p.adjust<0.05) %>% 
  mutate(cluster=factor(cluster,levels=1:length(unique(cluster)))) %>% 
  mutate(group=factor(group,levels=c("AZS","OLI","AZO"))) %>% 
  group_by(Description) %>% 
  mutate(group_num = n()) %>% 
  ungroup() %>% 
  arrange(desc(group_num),desc(cluster),desc(group),-p_adj) %>%
  # mutate(Description=factor(Description,levels=unique(.$Description)[c(2,1,3,4,6,7,5,8,16,18,9,11,12,10,13,15,17,14)]))
  mutate(Description=factor(Description,levels=unique(Description)))
write.table(all_up,file = "./outputdata/all_up.txt",sep = "\t",
            col.names = T,row.names = F,quote = F)
write.table(unique(all_up[2:3]),file = "./outputdata/all_up_GOterm.txt",sep = "\t",
            col.names = F,row.names = F,quote = F)


all_down <- rbind(AZS_down,OLI_down,AZO_down) %>% 
  mutate(p_adj=-log10(p.adjust)) %>% 
  mutate(NES=-NES) %>% 
  na.omit() %>% 
  filter(p.adjust<0.05) %>% 
  mutate(cluster=factor(cluster,levels=1:length(unique(cluster)))) %>% 
  mutate(group=factor(group,levels=c("AZS","OLI","AZO"))) %>% 
  group_by(Description) %>% 
  mutate(group_num = n()) %>% 
  ungroup() %>% 
  arrange(desc(group_num),desc(cluster),desc(group),-p_adj) %>%
  # mutate(Description=factor(Description,levels=unique(.$Description)[c(3,2,1,7,9,4,8,5,6,15,11,12,13,14,16,10,17,19,18)]))
  mutate(Description=factor(Description,levels=unique(Description)))
write.table(all_down,file = "./outputdata/all_down.txt",sep = "\t",
            col.names = T,row.names = F,quote = F)
write.table(unique(all_down[2:3]),file = "./outputdata/all_down_GOterm.txt",sep = "\t",
            col.names = F,row.names = F,quote = F)

### 4.ggplot photo ####
pdf(file = "./photo/Fig2C.all_up.pdf",
    width = 8.8,height = 5)
ggplot(all_up,aes(x=group,y=Description,color=p_adj,size=NES))+ 
  geom_point()+
  theme_bw()+
  facet_grid(cluster~.,scales = "free_y",space = "free_y",drop = F)+
  scale_color_gradient(high = '#ED0000FF',low = '#00468BFF')+
  scale_x_discrete(expand = c(0,1))+
  scale_y_discrete(expand = c(0,0.8))+
  scale_size_continuous(breaks = c(1.6,1.8,2.0),labels = c("1.6","1.8","2.0"))+
  labs(x=NULL,y=NULL,color="-log10(adjusted P)")+
  guides(color=guide_colorsteps(order=0),size=guide_legend(order=1))+
  theme(plot.margin = margin(0.4,0.4,0.4,0.4,'cm'),
        strip.text = element_blank(),
        panel.spacing = unit(0.1, "cm"),
        axis.title = element_text(size = 12,face = 'bold',hjust = 0.5),
        axis.text.y  = element_text(size = 10,face = 'bold',hjust = 1),
        axis.text.x  = element_text(size = 10,face = 'bold',hjust = 1,angle = 30),
        legend.title = element_text(size = 11,face = 'bold',hjust = 0),
        plot.title = element_text(size = 14,face = 'bold',hjust = 0.5))
dev.off()

pdf(file = "./photo/Fig2D.all_down.pdf",
    width = 8,height = 5)
ggplot(all_down,aes(x=group,y=Description,color=p_adj,size=NES))+ 
  geom_point()+
  theme_bw()+
  facet_grid(cluster~.,scales = "free_y",space = "free_y",drop = F)+
  scale_color_gradient(high = '#ED0000FF',low = '#00468BFF')+
  scale_x_discrete(expand = c(0,1))+
  scale_y_discrete(expand = c(0,0.8))+
  scale_size_continuous(breaks = c(1.4,1.8,2.2),labels = c("-1.4","-1.8","-2.2"))+
  labs(x=NULL,y=NULL,color="-log10(adjusted P)")+
  guides(color=guide_colorsteps(order=0),size=guide_legend(order=1),)+
  theme(plot.margin = margin(0.4,0.4,0.4,0.4,'cm'),
        strip.text = element_blank(),
        panel.spacing = unit(0.1, "cm"),
        axis.title = element_text(size = 12,face = 'bold',hjust = 0.5),
        axis.text.y  = element_text(size = 10,face = 'bold',hjust = 1),
        axis.text.x  = element_text(size = 10,face = 'bold',hjust = 1,angle = 30),
        legend.title = element_text(size = 11,face = 'bold',hjust = 0),
        plot.title = element_text(size = 14,face = 'bold',hjust = 0.5))
dev.off()

##Fig2E number of pachytene piRNA
library(ggplot2)
library(tidyr)
library(dplyr)
library(readxl)

data <- read_excel("piRNA.xlsx", sheet = "Sheet1")
colnames(data) <- c("Period", "AZS_Up", "AZS_Down", "OLI_Up", 
                    "OLI_Down", "AZO_up", "AZO_down", "Not_detected")

data_long <- data %>%
    filter(!is.na(Period)) %>%
  select(Period, AZS_Up, AZS_Down, OLI_Up, OLI_Down, AZO_up, AZO_down, Not_detected) %>%
  pivot_longer(cols = -Period, 
               names_to = "Category", 
               values_to = "Count") %>%
  mutate(
    Disease = case_when(
      Category == "Not_detected" ~ "AZO",
      grepl("AZS", Category) ~ "AZS",
      grepl("OLI", Category) ~ "OLI", 
      grepl("AZO", Category) ~ "AZO"
    ),
    Direction = case_when(
      Category == "Not_detected" ~ "Not_detected",
      grepl("_Up|_up", Category) ~ "Up",
      grepl("_Down|_down", Category) ~ "Down"
    ),
    Count = as.numeric(Count)
  ) %>%
  select(-Category)

# 
stack_data <- data_long %>%
  pivot_wider(names_from = Period, values_from = Count)

stack_data <- stack_data %>%
  mutate(
    Direction_ordered = case_when(
      Disease == "AZO" ~ factor(Direction, levels = c("Up", "Down", "Not_detected")),
      TRUE ~ factor(Direction, levels = c("Up", "Down"))
    )
  )


library(ggbreak)
library(patchwork) 
stack_data <- stack_data %>%
  mutate(Disease = factor(Disease, levels = c("AZS", "OLI", "AZO")))

pdf('Fig2E.barchart of pachytene piRNA.pdf')
ggplot() +
  geom_bar(data = stack_data, 
           aes(x = Direction_ordered, y = Total, fill = Direction_ordered),  # 修改：根据方向设置填充色
           stat = "identity", width = 0.5, 
           alpha = 0.8, position = position_dodge2(preserve = "single")) +
  geom_bar(data = stack_data, 
           aes(x = Direction_ordered, y = Pachytene), 
           stat = "identity", width = 0.5, alpha = 0.8, 
           fill = "#FF6B6B",  # color of Pachytene
           position = position_dodge2(preserve = "single")) +
  # 添加标签
  geom_text(data = stack_data,
            aes(x = Direction_ordered, y = Pachytene, label = Pachytene, group = Direction_ordered), 
            position = position_dodge2(width = 0.7, preserve = "single"),
            vjust = 0.5, size = 3, color = "white", fontface = "bold") +
  geom_text(data = stack_data,
            aes(x = Direction_ordered, y = Total, label = Total, group = Direction_ordered), 
            position = position_dodge2(width = 0.7, preserve = "single"),
            vjust = -0.5, size = 3, fontface = "bold") +
  facet_wrap(~ Disease, scales = "free_x", nrow = 1) +
  labs(title = "不同疾病类型中piRNA表达变化数量",
       x = "表达方向",
       y = "piRNA数量",
       fill = "表达方向") +  # 修改：图例标题改为"表达方向"
  # 修改：自定义颜色比例尺
  scale_fill_manual(
    values = c(
      "Up" = "#FF6B9D",    # 粉红色
      "Down" = "#4ECDC4",  # 青蓝色
      "Not_detected" = "#FFD166"  # 金黄色
    ),
    breaks = c("Up", "Down", "Not_detected"),  # 指定图例顺序
    labels = c("上调", "下调", "未检测到")  # 可选：自定义图例标签
  ) +
  scale_x_discrete(labels = function(x) {
    ifelse(x == "Not_detected", "Not_detected", x)
  }) +
  scale_y_continuous(expand = c(0,0)) +
  expand_limits(y = 11000) +
  scale_y_break(c(1000, 3000), scales = 0.1, ticklabels = c(3000, 4000, 5000), space = 0.1) + 
  scale_y_break(c(5000, 9000), scales = 0.1, ticklabels = c(9000, 9500, 10000), space = 0.1) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(), 
    plot.title = element_text(hjust = 0.5, face = "bold"),
    strip.background = element_rect(fill = "lightgray"),
    legend.position = "top"
  )
dev.off()

###Fig2F-G
len_5base <- data.frame(read.table('DE_len_5base.txt',header = T,row.names = 1))
pdf('piRNA_len_5base_R_UP.pdf',width = 8,height = 5,pointsize = 10)
barplot(t(data.matrix(len_5base))/1000/126,ylab='Average number of piRNA(X1000)',col=c('red','blue','green','orange'))
legend("topleft",legend =c('G','U','C','A'),cex=0.8,pch=15,col=c('orange','green','blue','red'))
dev.off()

###Fig2H. details in code of WGCNA

## Fig2I. boxplot of origin scores by cell type between groups
origin <- data.frame(read_xlsx('TableS3. Origin score of CIBERSOTx using scRNA data of testis.xlsx'))
origin_score <- origin %>%
  mutate(across(2:13, as.numeric))
origin_score$group <- factor(origin$Group, 
                             levels = c('NOR','AZS','OLI','AZO'))
groups_score = rep(c("NOR","AZS","OLI","AZO"),times=c(101,128,93,97)) # all sample passed QC
score_diff <- data.frame(group = rep(groups_score[1:419],5),
                         cell = rep(c('SSCs','Late primary scytes','Round Stids','Sperm','Sertoli Cells'),times=c(419,419,419,419,419)),
                         score = c(origin_score$SSCs,origin_score$Late.primary.Scytes,origin_score$Round.Stids,origin_score$Sperm,origin_score$Sertoli.Cells))

p<-ggplot(score_diff, aes(fill=factor(group,level=c("NOR","AZS","OLI","AZO")), y=score,x=factor(cell,level=c('SSCs','Late primary scytes','Round Stids','Sperm','Sertoli Cells')))) +
  geom_boxplot(show.legend = NA,outlier.size = 0.2)+ 
  theme_void()
pdf('Fig2I.Origin_diff_cell_boxplot.pdf',width=9,height=6)
p+ theme(legend.text = element_text(size=10),legend.title  = element_blank(),
         axis.text.x = element_text(angle = 45),axis.text.y = element_text(size=10),axis.line = element_line(),axis.ticks.x = element_line(),
         axis.ticks.length.y = unit(.05, "cm"),axis.ticks.y=element_line(linewidth = 0.5),axis.title.y = element_text(angle=90,size=12))
dev.off()

################### Figure 3
#Fig3A. volcano plot of DE in AZO with marked genes
library(ggrepel)
library(dplyr)
DE_AZO <- data.frame(read.table('D:/项目/精浆cfRNA/分析结果/Exp/DEG/DEG/20230815_zq_semenDEGs/outputdata/mlncRNA_count_CF.W_DEGs.txt',header = T,row.names = 1,sep="\t"))
gene_data <- data.frame(Gene=DE_AZO$gene,Log2FC=DE_AZO$log2FoldChange,PValue=DE_AZO$padj)
gene_data$NegLog10P <- -log10(gene_data$PValue)
log2fc_threshold <- 1
pval_threshold <- 0.05

gene_data <- gene_data %>%
  mutate(Significant = case_when(
    NegLog10P > -log10(pval_threshold) & Log2FC > log2fc_threshold ~ "Up",
    NegLog10P > -log10(pval_threshold) & Log2FC < -log2fc_threshold ~ "Down",
    TRUE ~ "Not Sig"
  ))
genes_of_interest <- c("PRM1","SPATA3","SPATA42","PRM2","DMC1","DMRT1","MEIOB",
                       "PDHA2","SPO11","TDRD9","TEX15","MEI1","PNLDC1","HIWI","MSH4","SPATA22")
#"MEIOB","NR5A1","MEI1","TEX11"
# 修改Label列
gene_data <- gene_data %>%
  mutate(Label = if_else(
    Gene %in% genes_of_interest,
    as.character(Gene),
    ""
  ))
p <- ggplot(data = gene_data, aes(x = Log2FC, y = NegLog10P)) +
  geom_point(aes(color = Significant), alpha = 0.6, size = 1.5) + # 根据显著性上色
  scale_color_manual(values = c("Down" = "lightblue", "Not Sig" = "grey", "Up" = "pink")) +
  #theme_minimal() + # 简洁的主题
  theme_classic()+
  labs(
    x = expression("Log"[2]*" Fold Change"),
    y = expression("-Log"[10]*" P-value"),
    title = "",
    color = "Regulation"
  ) +
  geom_vline(xintercept = c(-log2fc_threshold, log2fc_threshold), linetype = "dashed", color = "black", alpha = 0.5) +
  geom_hline(yintercept = -log10(pval_threshold), linetype = "dashed", color = "black", alpha = 0.5)
p_with_labels <- p + geom_text_repel(
  data = subset(gene_data, Label != ""), # 只对Label不为空的点进行标注
  aes(label = Label),
  size = 5,
  box.padding = 0.6, # 调整标签与点之间的距离
  point.padding = 0.3,
  max.overlaps = 30, # 最大允许的重叠数，可调整
  segment.color = 'grey50', # 连接线的颜色
  show.legend = FALSE # 不显示标签的图例
)
pdf('Fig3A.DE_AZO_volcano.pdf')
print(p_with_labels)
dev.off()


#Fig3B legend of GO cluster,network was generated from metascape
library('RColorBrewer')
colors <- c(brewer.pal(9,'Set1'),brewer.pal(12,'Set3'))
GO <- c("male gamete generation","cilium movement","fertilization","meiotic cell cycle",
        "axonemal dynein complex assembly","acrosome assembly","Fertilization","sperm DNA condensation",
        "Male infertility","retrotransposon silencing by heterochromatin formation","acrosome reaction",
        "Motor proteins","NABA CORE MATRISOME","sperm capacitation","gonad development",
        "regulation of reproductive process","female meiotic nuclear division","regulation of mitotic nuclear division",
        "regulation of cilium movement","inner dynein arm assembly")
pdf('Fig3B.AZO_GO_legend.pdf')
plot.new()
legend('topleft',pch=15,col=colors,legend = GO,cex=0.8,bty='n')
dev.off()

###Fig3C cytoscape of ceRNA network,details in code of ceRNA_pipeline


#Fig3D. expression of RNA in ceRNA network 
Genes_TPM <- data.frame(read.table("Genes_TPM.txt",header = T,row.names = 1))
groups = rep(c("NOR","AZS","OLI","AZO"),times=c(101,128,93,97))
miRNA_TPM <- data.frame(read.table('miRNA_TPM.txt',header = T,row.names = 1))

exp_gene <- as.data.frame(cbind(t(log2(Genes_TPM[,1:419]+1)),t(log2(miRNA_TPM[,1:419]+1))))
CE <- data.frame(group = rep(c(groups[1:101],groups[323:419]),3),
                 genes= as.factor(c(rep('hsa-miR-125a-3p',198),rep('YBX2',198),rep('CDKN2B-AS1',198))),
                 exp=c(exp_gene$`hsa-miR-125a-3p`[1:101],exp_gene$`hsa-miR-125a-3p`[323:419],exp_gene$YBX2[1:101],exp_gene$YBX2[323:419],exp_gene$`CDKN2B-AS1`[1:101],exp_gene$`CDKN2B-AS1`[323:419]))
exp_gene$group <- as.factor(groups)
pdf('Fig3D.YBX2_ce_exp_violin.pdf',width=5,height=4)
ggplot(CE, aes(x=factor(genes,levels = c('hsa-miR-125a-3p','YBX2','CDKN2B-AS1')), y=exp,fill=group)) + 
  geom_violin(scale = 'width')+
  theme_classic() +
  labs(title = "",x='',y='log2(TPM +1)') +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45,hjust = 1,vjust = 1))
dev.off()

#Fig3E. generated by Biorender
#Fig3F-G, download from online database

############## Fig 4
#Fig4A. pipeline of model generated by Biorender

#Fig4B-C. scatter of predicted value(sperm number and PR)
library(ggplot2)
library(FNN)
library(broom)
# 读取数据
df <- read.csv("num_scatter_plot.csv", row.names = 1)
df <- read.csv("PR_scatter_plot.csv", row.names = 1)
# 定义距离阈值
dist_threshold <- 10  # 调整为合理的距离阈值
# 使用get.knnx找到每个点的邻近点
train_data <- as.matrix(df[, c("x", "y")])
test_data <- as.matrix(df[, c("x", "y")])
# 计算所有点之间的距离矩阵
dist_matrix <- dist(train_data, method = "euclidean")
# 将距离矩阵转换为邻接矩阵
adj_matrix <- as.matrix(dist(train_data, method = "euclidean")) <= dist_threshold
# 计算每个点的邻近点数量
neighbor_counts <- rowSums(adj_matrix) - 1  # 减去自身
# 将邻近点数量作为颜色变量
df$color_value <- neighbor_counts
# 进行线性回归并提取统计信息
fit <- lm(y ~ x, data = df)
summary_fit <- summary(fit)
conf_int <- confint(fit)
# 提取R²、RMSE和Pearson相关系数
r_squared <- summary_fit$r.squared
rmse <- sqrt(mean(residuals(fit)^2))
pearson_corr <- cor(df$x, df$y)
# 创建散点图，并添加拟合直线和置信区间
p <- ggplot(df, aes(x = x, y = y)) +
  geom_point(aes(color = color_value), size = 3) +  # 根据color_value设置颜色渐变
  geom_smooth(method = "lm", se = TRUE, color = "black", fill = "gray60", alpha = 0.3) +  # 添加线性回归拟合直线和置信区间
  scale_color_gradient(name = "n_neighbors", low = "darkblue", high = "yellow") +  # 设置颜色渐变范围和legend标题
  labs(title = "Scatter Plot with Fitted Line and Gradient Colors",
       x = "Sperm Count",
       y = "Predicted Sperm Count") +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +  # 去除背景网格
  theme(axis.line = element_line(colour = "black", size = 0.5)) +  # 显示坐标轴的线本身
  theme(axis.title.x = element_text(size = 14 * 1.5), axis.title.y = element_text(size = 14 * 1.5)) +  # 坐标轴标题文字大小增加一倍
  theme(axis.text.x = element_text(size = 12 * 1.5), axis.text.y = element_text(size = 12 * 1.5)) +  # 坐标轴刻度文字大小增加一倍
  theme(legend.title = element_text(size = 12 * 1.5)) +  # legend标题文字大小增加一倍
  annotate("text", x = min(df$x), y = max(df$y),
           label = paste("R² =", round(r_squared, 2), "\nRMSE =", round(rmse, 2), "\nPearson =", round(pearson_corr, 2)),
           hjust = 0, vjust = 1, color = "black", size = 4)

pdf("Fig4B.num_scatter.final.pdf")
print(p)
dev.off()
pdf("Fig4C.PR_scatter.final.pdf")
print(p)
dev.off()

#Fig4D-G details in jupter file of constructing models(model_**)
